name: Deploy to Netlify

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install dependencies (if needed)
        run: |
          if [ -f "package-lock.json" ]; then
            npm ci
          else
            echo "No package-lock.json found, skipping npm install"
          fi
        
      - name: Validate HTML
        run: |
          # Basic HTML validation
          if ! grep -q '<!DOCTYPE html>' index.html; then
            echo "Error: Missing DOCTYPE declaration"
            exit 1
          fi
          if ! grep -q '<title>' index.html; then
            echo "Error: Missing title tag"
            exit 1
          fi
          echo "HTML validation passed"
          
      - name: Check for required elements
        run: |
          # Check for required content
          if ! grep -q 'CycleCoach' index.html; then
            echo "Error: Missing CycleCoach branding"
            exit 1
          fi
          if ! grep -q 'Train Smarter' index.html; then
            echo "Error: Missing main headline"
            exit 1
          fi
          echo "Content validation passed"

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v2.0
        with:
          publish-dir: '.'
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1

  preview:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4
      
      - name: Deploy Preview to Netlify
        uses: nwtgck/actions-netlify@v2.0
        with:
          publish-dir: '.'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Preview deploy for PR #${{ github.event.number }}"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1 